### ISSUE TITLE
Feature Request: Ability to set native query endpoint URL

### ISSUE THREAD

**Issue by tomasko126** [oskar11120/Apache.Druid.Querying#4]
Hi,

Our company has opted into using [Imply's Polaris SaaS](https://imply.io/imply-fully-managed-dbaas-polaris/), which is basically Druid DBaaS. However, the endpoint for sending native queries is different from the [hard-coded path](https://github.com/oskar11120/Apache.Druid.Querying/blob/master/Apache.Druid.Querying/QueryExecution.cs#L285).

Would it be possible to add a feature, which would allow us to set that endpoint URL?
For now, I had to create an intercepting handler, which should be deemed as a workaround to this issue.

P.S.: I'd like to thank you for creating this library, which makes it possible for us to run native queries against the Druid DB in our .NET code base 🙏

**Comment by oskar11120** [comment]
Hi. Didn't know the endpoint uri could be different. Will parameterize it.
